### ISSUE TITLE
Fix Header styles

### ISSUE THREAD

**Issue by renatojobal** [pettnaut/frontend-code#17]
# Goal: Get better style into the header
# Acceptances criteria
- Make the header like the high fidelity design
# Descripcion
Currently the header is looking in this way:
![image](https://user-images.githubusercontent.com/35740463/95132044-bf062480-0724-11eb-995e-ade1aeb44978.png)

The new header style should look like this one:
![image](https://user-images.githubusercontent.com/35740463/95133102-633c9b00-0726-11eb-8759-62fcc4755d55.png)
So:
- Change the background color for this one: #5D34AF
- Add Pettnaut's logo at the beginning. The logo is located at `src/assests/logo.svg` (We know we have a typo in the folder name)

**Comment by klee214** [comment]
If you don't mind I would like to work on this!

**Comment by renatojobal** [comment]
Thank you so much @klee214 . Go ahead!
