### ISSUE TITLE
Create card component

### ISSUE THREAD

**Issue by renatojobal** [pettnaut/frontend-code#20]
# Goal: Create the card component for a pet preview
# Description:
Create a function component called `Card.js` with the style below. This component should receive this arguments into the props: `imageURL` , `name`, `description`. Use the Card react component.

You can see how your component looks like running storybook. 

# Files to create
- `src/components/card/Card.js`
- `src/components/card/card.css`
- `src/stories/Card.stories.js`

# Output
The design should like this:
![image](https://user-images.githubusercontent.com/35740463/95261707-7ddb4680-07f0-11eb-8f7a-74338c72a86d.png)

# Useful info
You may import this on your storybook component :
``` 
import React from 'react';
import "bootstrap/dist/css/bootstrap.css";
import '../components/card/card.css';
import Card from '../components/card/Card';
```

**Comment by cesardlinx** [comment]
If you don't mind I would like to work on this!

**Comment by renatojobal** [comment]
Sure @cesardlinx . We will appreciate your job! If have any question please let us know.
