### ISSUE TITLE
Keep footer when it belongs

### ISSUE THREAD

**Issue by renatojobal** [pettnaut/frontend-code#23]
## Why?
Now the footer is being showing like this:
![image](https://user-images.githubusercontent.com/35740463/95641891-9bb3e000-0a6a-11eb-9197-2768a0f7d9bf.png)

## Descripcion
The footer should be at the **bottom** of every page. Even when the content is not enough to fill the screen.

**Comment by cesardlinx** [comment]
I would like to fix that if you don't mind
