### ISSUE TITLE
[Card] Create a componente for the footer

### ISSUE THREAD

**Issue by gabygm** [pettnaut/frontend-code#7]
# Goal: Have a footer for all pages 

# Acceptances criteria
- Create a component for the footer with react
- Adapt according to the design showed below

# Output
the design should like this:
![image](https://user-images.githubusercontent.com/35740463/94997618-fed8da80-0571-11eb-901e-b4ce6a2b450e.png)

**Comment by ayush-git228** [comment]
I have pulled a request for footer component with style added, please check.
