### ISSUE TITLE
[Card] Create component header page

### ISSUE THREAD

**Issue by gabygm** [pettnaut/frontend-code#8]
# Gaol: have header in all page
# Acceptances Criteria:

- Create component in react for the header
- Adapt this component according to the design, showed below

# Output:
Design should be like this:
![image](https://user-images.githubusercontent.com/35740463/94996652-8b33cf00-056b-11eb-91a5-51df83092700.png)

**Comment by AlcidesA** [comment]
I would love to work on this, can you assign to me ?

**Comment by renatojobal** [comment]
Thanks for the interest @AlcidesA but sorry. Someone has already mentioned this issue in a pull request.
